- name: Autoupdate in cron
  cron:
    name: apt autoupdate
    minute: "0"
    job: /usr/bin/apt -y update && /usr/bin/apt -y full-upgrade && /usr/bin/apt -y autoremove && [ -f /var/run/reboot-required ] && reboot
