- name: Autoupdate in cron
  cron:
    name: apt autoupdate
    minute: "0"
    job: /usr/bin/apt-get -y update && /usr/bin/apt-get -y dist-upgrade && /usr/bin/apt-get -y autoremove && [ -f /var/run/reboot-required ] && reboot
