- name: Get local set in file
  shell: grep "^LANG=en_US.UTF-8" /etc/default/locale
  register: locale_contents
  changed_when: false
  ignore_errors: true
- name: Set the locale via raspi-config
  command: raspi-config nonint do_change_locale "en_US.UTF-8"
  when: locale_contents.stdout == ""
- name: Get current keyboard and store as var
  shell: cat /etc/default/keyboard
  register: keyboard_contents
  changed_when: false
- name: Set the keyboard layout via raspi-config
  command: raspi-config nonint do_configure_keyboard "us"
  when: keyboard_contents.stdout.find('XKBLAYOUT="us"') == -1
- name: set timezone
  command: raspi-config nonint do_change_timezone "US/Central"
  when: ansible_date_time["tz"] != "CDT"
