- hosts: pi_default
  become: true
  handlers:
    - import_tasks: ../handlers/restart_sshd.yml
    - import_tasks: ../handlers/restart_system.yml
  tasks:
    - import_tasks: ../tasks/apt_raspi.yml
    - import_tasks: ../tasks/raspi-config.yml
    - import_tasks: ../tasks/fish.yml
    - import_tasks: ../tasks/editor.yml
    - import_tasks: ../tasks/auto_update.yml
    - import_tasks: ../tasks/git_config.yml
    - import_tasks: ../tasks/ssh_secure.yml
    - import_tasks: ../tasks/systemd_logging.yml
    - import_tasks: ../tasks/reboot_check.yml
